title = "Server file configuration"

# The settings for the automation of the cache of the program.
[Crons]
# Enable token cleaning (removing epxired tokens)
# default: true
clean_tokens = true

# The interval in which the loop for removing the expried tokens is run
# The clean_tokens needs to be true for this setting to have an impact
# default: 1800 seconds (30 minutes)
clean_tokens_interval = 1800 #seconds

# Enable test cron functions
# default: false
enable_test_crons = false

# The interval in which the checks for actions are run
# default: 300 seconds (5 minutes)
check_actions_interval = 300 #seconds

# The status codes used by the program:
[Status_codes]

# The code when everything goes according to plan
# The default code is 0
success = 0

# The code when there is an error
# The default code is 84
error = 1

# Debug mode, the mode that shows everything (almost) that is going on in the server
# Be cautious, you may get a mind overflow with all the information.
[Debug_mode]
# This is a variable that will act on the general server on if to activate or not the debug mode
# The default value is false
debug = false

# Arg, here comes the test territory
[Test]

[Test.port]
# This is the port that will be used by the server and the client during the automated testing
# The default port is 6000
port = 6000

[Test.hosts]
# This is the host on which the server will be listening when it will be waiting for queries
# The default value is "0.0.0.0"
server = "0.0.0.0"

# This is the host on which the client will make it's requests.
# The default value is "http://127.0.0.1"
client = "http://127.0.0.1"
